### ISSUE TITLE
Error with headreco in some cases

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#10]
Dear SimBibs developers, 

I'm trying the headreco with differents MRI and in some case, I got these errors. 

Do you have any idea about this error? 

Any solutions? 

Thanks in advance.

Regards 
Takfarinas 

![image](https://user-images.githubusercontent.com/37831900/65188076-20345a80-da33-11e9-8f76-5f832f2e7047.png)

------------------------------------------------------------------------
  Warning:cat_io_report:CATgui: Incomplete report creation in cat_io_report because of incomplete CAT parameters.

Print 'Graphics' figure to: 
  C:\Users\33649\Documents\MATLAB\MRIdata\anand new data\SVRegTestData\5235HD\m2m_5235HD\segment\cat\report\catreport_T1fs_conform.pdf
Failed  'CAT12: Segmentation'
Error using cat_main_gintnorm (line 376)
Bad tissue contrast (C=1489.01, G=1435.84, W=1768.00)

In file "C:\Users\33649\AppData\Local\SimNIBS\miniconda3\envs\simnibs_env\Lib\site-packages\simnibs\resources\spm12\toolbox\cat12\cat_main_gintnorm.m" (v1159), function "cat_main_gintnorm" at line 376.
In file "C:\Users\33649\AppData\Local\SimNIBS\miniconda3\envs\simnibs_env\Lib\site-packages\simnibs\resources\spm12\toolbox\cat12\cat_main.m" (v1274), function "cat_main" at line 666.
In file "C:\Users\33649\AppData\Local\SimNIBS\miniconda3\envs\simnibs_env\Lib\site-packages\simnibs\resources\spm12\toolbox\cat12\cat_run_job.m" (v1245), function "cat_run_job" at line 1185.
In file "C:\Users\33649\AppData\Local\SimNIBS\miniconda3\envs\simnibs_env\Lib\site-packages\simnibs\resources\spm12\toolbox\cat12\cat_run_newcatch.m" (???), function "cat_run_newcatch" at line 18.
In file "C:\Users\33649\AppData\Local\SimNIBS\miniconda3\envs\simnibs_env\Lib\site-packages\simnibs\resources\spm12\toolbox\cat12\cat_run.m" (v1245), function "run_job" at line 395.
In file "C:\Users\33649\AppData\Local\SimNIBS\miniconda3\envs\simnibs_env\Lib\site-packages\simnibs\resources\spm12\toolbox\cat12\cat_run.m" (v1245), function "cat_run" at line 161.

The following modules did not run:
Failed: CAT12: Segmentation

Error using MATLABbatch system
Job execution failed. The full log of this run can be found in MATLAB command window, starting with the lines (look for the line showing the exact #job as
displayed in this error message)
------------------
Running job #1
------------------
 
» Warning: A value of class "com.mathworks.hwsmanagement.InstalledSupportPackage$Builder" was indexed with no subscripts specified. Currently the result of this
operation is the indexed value itself, but in a future release, it will be an error. 
> In matlab.supportpackagemanagement.internal.getInstalledSupportPackagesInfo (line 44) 
»

**Comment by guilhermebs** [comment]
Can you please send us your log file? It should be in `m2m_ADNI\headreco_log.html`

**Comment by oulap** [comment]
CAT12 is suggesting that this could be an error in the affine registration. 
Can you check if the tissue probability maps align reasonably well with the input image?

You can find the maps in:
m2m_<subID>/segment/spm/c*_conform.nii

Just open those together with the input MRI in any standard viewer and you should be able to see if that's the problem.

**Comment by tmedani** [comment]
> Can you please send us your log file? It should be in `m2m_ADNI\headreco_log.html`

The log file is not long, here it is : 


2019-09-18 16:16:39 [DEBUG] c:\users\33649\appdata\local\simnibs\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\cli\headreco.py all ADNI ADNI_002_S_0685_MR_MP-RAGE__br_raw_20100716081357767_16.nii
2019-09-18 16:16:39 [INFO ] ========================================================================
2019-09-18 16:16:39 [INFO ] PREPARING VOLUMES FOR MESHING
2019-09-18 16:16:39 [INFO ] ========================================================================
2019-09-18 16:16:39 [INFO ] Copying input files to m2m_ADNI
2019-09-18 16:16:39 [INFO ] Copying T1fs.nii.gz to T1fs_conform.nii.gz
2019-09-18 16:16:40 [INFO ] Preparing to segment
2019-09-18 16:16:40 [INFO ] Starting MATLAB
2019-09-18 16:16:40 [INFO ] ========================================================================
2019-09-18 16:16:40 [DEBUG] Running matlab -nosplash -nodesktop -wait -logfile "C:\Users\33649\Documents\MATLAB\MRIdata\anand new data\SVRegTestData\ADNI_002_S_0685_MR_MP-RAGE__br_raw_20100716081357767_16\m2m_ADNI\segment\spmcat.log" -r "addpath('c:\Users\33649\AppData\Local\SimNIBS\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\msh','c:\Users\33649\AppData\Local\SimNIBS\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\resources\spm12');try,segment_SPM('c:\Users\33649\AppData\Local\SimNIBS\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\resources\templates','C:\Users\33649\Documents\MATLAB\MRIdata\anand new data\SVRegTestData\ADNI_002_S_0685_MR_MP-RAGE__br_raw_20100716081357767_16\m2m_ADNI\segment\spm\T1fs_conform.nii',[],0.01,3); segment_CAT('C:\Users\33649\Documents\MATLAB\MRIdata\anand new data\SVRegTestData\ADNI_002_S_0685_MR_MP-RAGE__br_raw_20100716081357767_16\m2m_ADNI\segment\cat\T1fs_conform.nii','c:\Users\33649\AppData\Local\SimNIBS\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\resources\templates',0);catch ME,rethrow(ME);end,exit;"
2019-09-18 16:47:11 [INFO ] Binarizing tissue probability maps
2019-09-18 16:47:15 [ERROR] Traceback (most recent call last):
  File "c:\users\33649\appdata\local\simnibs\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\cli\headreco.py", line 13, in 
    main()
  File "c:\users\33649\appdata\local\simnibs\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\cli\headreco.py", line 10, in main
    headmodel(sys.argv)
  File "c:\Users\33649\AppData\Local\SimNIBS\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\msh\headreco.py", line 274, in headmodel
    masks = hmu.binarize([nib.load(v).get_data() for v in fcat])
  File "c:\Users\33649\AppData\Local\SimNIBS\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\msh\hmutils.py", line 778, in binarize
    imgs = np.concatenate(tuple([v[...,np.newaxis] for v in volsi]), axis=3)
ValueError: need at least one array to concatenate

**Comment by guilhermebs** [comment]
Looks like SPM is failing.
Could you please send the log file over at

`m2m_ADNI\segment\spmcat.log`

**Comment by tmedani** [comment]
> Looks like SPM is failing.
> Could you please send the log file over at
> 
> `m2m_ADNI\segment\spmcat.log`
Here it is : 
[spmcat.log](https://github.com/simnibs/simnibs/files/3632511/spmcat.log)

**Comment by oulap** [comment]
It looks like SPM ran for about 5 minutes, which sounds a bit too fast to me.

Did you get any ouput files in the folder:

m2m_<subid>/segment/spm/

?

**Comment by tmedani** [comment]
> It looks like SPM ran for about 5 minutes, which sounds a bit too fast to me.
> 
> Did you get any ouput files in the folder:
> 
> m2m_/segment/spm/
> 
> ?

Hi,
The process is stopped after 5-10 min, 

There are outputs files in the  m2m_/segment/spm/

![image](https://user-images.githubusercontent.com/37831900/65648272-3740f280-dfc7-11e9-9262-a51f70b40230.png)

**Comment by oulap** [comment]
Thanks, did you check if the tissue probability maps (c*T1fs_conform.nii) overlap with the tissues in the MRI scan? I expect the overlap to be bad if this is indeed an issue with the affine registration.

**Comment by tmedani** [comment]
Thanks for your answer, 
Yes, they are totally off, and there is no overlap. 
Let me know please what I should do. 

Thank you

**Comment by oulap** [comment]
I couldn't open the link (it's complaining about user rights). 

In general this is an SPM-related issue, and the affine transformation needs to probably be initialized somehow differently. Currently, we don't have a way of passing in an initial transform to SPM12 in headreco, but I'll check the scans and see if we should add that feature.

**Comment by tmedani** [comment]
Thanks, 
I have just sent you permission to have access to the data.

**Comment by oulap** [comment]
Sorry for the delayed reply.

I actually managed to get this subject to run properly by switching off the SPM12 standard of using 'mni'-type affine registration. This will likely not solve all possible affine registration problems, but I'm wondering if we should add a flag, so that it's possible to change affine registration type SPM12 uses.

Another way would be to allow users to input an initial transformation to SPM12 to inform the affine registration.

**Comment by tmedani** [comment]
Dear @oulap and @guilhermebs,

Thank you for your answer, and sorry for my late reaction. 
I was traveling and working on other topics.

@oulap how can I reproduce your solution on my computer? 


@guilhermebs sorry for my late reply to this thread, 
I'm still interested to solve this problem. 
 
Thanks for your help. 

Kind regards 
Takfarinas

**Comment by oulap** [comment]
Hi Takfarinas,

Assuming you have Simnibs 3.0 or higher installed, you can go to:

<your_anaconda_path>/envs/simnibs_env/lib/python3.7/site-packages/simnibs/msh/

There you can find the file that runs SPM12, called "segment_SPM.m"
On line 112 you can turn off the mni-initialization by replacing 'mni' by ''

Then run the problematic scan again, and hopefully the affine registration now works.

Best,
Oula

**Comment by tmedani** [comment]
Hi Oula, 
Thank you, I will try it asap. 

In order to have the latest version of Simnibs, 
Should I uninstall the previous version and install the latest or there is a way to update it? 

Thanks & best regards 
Takfarinas

**Comment by oulap** [comment]
Hi Takfarinas,

If you open a command prompt (Windows) or terminal (Linux/Mac) and write:

update_simnibs

that should do it. This assumes that your current SimNIBS version is 3.0 or higher.

Best,
Oula

**Comment by tmedani** [comment]
Thank you.
