### ISSUE TITLE
pip install simnibs errors out

### ISSUE THREAD

**Issue by ulloaa** [simnibs/simnibs#105]
Hello, 

While trying to pip install 4.0 I get the following error (same pip install works for previous versions, even 4.0beta1):

```
pip install https://github.com/simnibs/simnibs/archive/refs/tags/v4.0.0.tar.gz

Collecting https://github.com/simnibs/simnibs/archive/refs/tags/v4.0.0.tar.gz
  Using cached https://github.com/simnibs/simnibs/archive/refs/tags/v4.0.0.tar.gz
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      running egg_info
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'simnibs/segmentation/atlases/charm_atlas_mni'
      adding license file 'LICENSE.txt'
      writing manifest file 'SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "setup.py", line 518, in <module>
          raise IOError('could not locate folder with console-scripts')
      OSError: could not locate folder with console-scripts
      [end of output]
```

My question is, did anything changed in the past few months that could be causing this error?

Thank you very much,

**Comment by ulloaa** [comment]
Actually, the following did work with no errors:

```
pip install simnibs-4.0.0-cp39-cp39-linux_x86_64.whl
```

**Comment by oulap** [comment]
Seems like you managed to sort out the error, so I'll close this. Feel free to re-open if you experience further problems.
