### ISSUE TITLE
SimNIBS 4 - TMSoptimize error Matlab and Python

### ISSUE THREAD

**Issue by ItayHadas** [simnibs/simnibs#106]
Hi!
I tried your TMSoptimize (https://simnibs.github.io/simnibs/build/html/documentation/opt_struct/tmsoptimize.html#tmsoptimize-doc) with simnibs 4 - and it gives me some errors:
in python:
`
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
`

in matlab:
`
Error using run_simnibs
There was an error running SimNIBS:
 /home/ipp/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.12) or chardet
 (5.0.0)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/ipp/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/cli/run_simnibs.py", line 7, in <module>
    from simnibs import run_simnibs
  File "/home/ipp/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/__init__.py", line 21, in <module>
    from .mesh_tools import *
  File "/home/ipp/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/mesh_tools/__init__.py", line 6, in <module>
    from .mesh_io import *
  File "/home/ipp/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/mesh_tools/mesh_io.py", line 49, in <module>
    from . import cgal
  File "/home/ipp/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/mesh_tools/cgal/__init__.py", line 1, in <module>
    from .create_mesh_surf import *
ImportError:
/home/ipp/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/mesh_tools/cgal/create_mesh_surf.cpython-39-x86_64-linux-gnu.so: undefined
symbol: __gmpq_add
`

Thanks so much!

**Comment by oulap** [comment]
Hi,

Did you use the 'direct' or 'ADM' approach for the optimization? Also could you provide the specs of the operating system and computer you are using to run simnibs? I can then try to reproduce this and sort it out.

Thanks!

**Comment by jkosciessa** [comment]
Hi all, @achetverikov and I stumbled upon the same issue with the command ```mni2subject_coords```. It seems to be caused by how the ```system()``` command works with MATLAB's internal ```LD_LIBRARY_PATH```.  In our case the path ```/opt/gcc/7.2.0/lib64``` is relevant. Appending this path for MATLAB as described [here](https://www.mathworks.com/help/matlab/matlab_external/changing-environment-variables-for-shell-escape-functions.html) unfortunately does not fix the issue, as the MATLAB paths are added first. A manual fix such as the one below does work, but requires rewriting the functions (credit for the solution goes to @achetverikov). In this solution, the ```system()``` command first sets the desired ```LD_LIBRARY_PATH```:

```
parameters.ld_library_path='/opt/gcc/7.2.0/lib64';

function coords_sub = mni2subject_coords_LDfix(coords_mni, subdir, parameters, transformation_type)
[...]
% include LD fix
if isfield(parameters,'ld_library_path')
    ld_command = sprintf('export LD_LIBRARY_PATH="%s"; ', parameters.ld_library_path);
else
    ld_command = '';
end

% Run mni2subject_coords
[status,result] = system(sprintf('%s%s/mni2subject_coords -m %s -s %s -o %s -t %s;', ...
    ld_command, parameters.simnibs_bin_path, subdir, fn_in, fn_out, transformation_type))
```

This hack solves the issue, but a more general solution would of course be fantastic, rather than having re-specify the system call in every instance where python code is invoked.

**Comment by oulap** [comment]
Thanks for reporting this plus the fix. I'll try to reproduce this and see if I can figure out a more general solution.

**Comment by oulap** [comment]
Hi,

Does this solution work for you?

https://neuroimage.usc.edu/forums/t/brainstorm-not-recognising-path-or-command-to-simnibs-4-0-0/38963/7

Basically add this line to the matlab file:

setenv('LD_LIBRARY_PATH', sprintf('</path/to/simnibs>/external/lib/linux:%s', getenv('LD_LIBRARY_PATH')))

to prepend the correct libraries to the LD path.

**Comment by CEMNIS** [comment]
Hello,

Thank you for your answer.

I tested your solution with the LD_LIBRARY_PATH, and now my optimization and the rest of my processing work. Thank you very much.

**Comment by oulap** [comment]
Great, I'll close this one.
