### ISSUE TITLE
installation error from setup.py

### ISSUE THREAD

**Issue by ggrrll** [simnibs/simnibs#121]
Hi, 

I am trying to install from the repo, with the standard `python3 setup.py install --user` and I get:

```
building 'simnibs.mesh_tools.cython_msh' extension
error: unknown file type '.pyx' (from 'simnibs/mesh_tools/cython_msh.pyx')
```

any idea? 

thanks

ps: the `build` folder gets created, so the issue is after

**Comment by ggrrll** [comment]
`pip install cython` and  libraries according to https://itslinuxfoss.com/fix-command-x86-64-linux-gnu-gcc-failed-with-exit-status1/ 
still gives
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

can you maybe list what libraries do you have ? or what OS do you use? 
thanks

**Comment by ggrrll** [comment]
`pip install cython` and  libraries according to https://itslinuxfoss.com/fix-command-x86-64-linux-gnu-gcc-failed-with-exit-status1/ 
still gives
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

can you maybe list what libraries do you have ? or what OS do you use? 
thanks

**Comment by ggrrll** [comment]
also in macOS , I get many warning and at the end:

````
/[mypath]/simnibs/CGAL-5.4/include/CGAL/config.h:127:10: fatal error: 'boost/config.hpp' file not found
#include <boost/config.hpp>
         ^~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
```

**Comment by ggrrll** [comment]
also, `pip install . ` returns

```
Processing [mypath]
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      running egg_info
      creating /private/var/folders/rr/yjw9dl1j06z0cdz1rz3xf6z80000gn/T/pip-pip-egg-info-s0ajvcew/simnibs.egg-info
      writing /private/var/folders/rr/yjw9dl1j06z0cdz1rz3xf6z80000gn/T/pip-pip-egg-info-s0ajvcew/simnibs.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/rr/yjw9dl1j06z0cdz1rz3xf6z80000gn/T/pip-pip-egg-info-s0ajvcew/simnibs.egg-info/dependency_links.txt
      writing entry points to /private/var/folders/rr/yjw9dl1j06z0cdz1rz3xf6z80000gn/T/pip-pip-egg-info-s0ajvcew/simnibs.egg-info/entry_points.txt
      writing requirements to /private/var/folders/rr/yjw9dl1j06z0cdz1rz3xf6z80000gn/T/pip-pip-egg-info-s0ajvcew/simnibs.egg-info/requires.txt
      writing top-level names to /private/var/folders/rr/yjw9dl1j06z0cdz1rz3xf6z80000gn/T/pip-pip-egg-info-s0ajvcew/simnibs.egg-info/top_level.txt
      writing manifest file '/private/var/folders/rr/yjw9dl1j06z0cdz1rz3xf6z80000gn/T/pip-pip-egg-info-s0ajvcew/simnibs.egg-info/SOURCES.txt'
      reading manifest file '/private/var/folders/rr/yjw9dl1j06z0cdz1rz3xf6z80000gn/T/pip-pip-egg-info-s0ajvcew/simnibs.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'simnibs/segmentation/atlases/charm_atlas_mni'
      adding license file 'LICENSE.txt'
      writing manifest file '/private/var/folders/rr/yjw9dl1j06z0cdz1rz3xf6z80000gn/T/pip-pip-egg-info-s0ajvcew/simnibs.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/gianrocco/Documents/GitHub/simnibs/setup.py", line 518, in <module>
          raise IOError('could not locate folder with console-scripts')
      OSError: could not locate folder with console-scripts
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
