### ISSUE TITLE
Uncaught Exception in Charm

### ISSUE THREAD

**Issue by iPsych** [simnibs/simnibs#128]
Charm process stops with uncaught exception.
I guess it might be numpy version issue or mismatch of input-output dimension.

```
INFO: Writing out normalized images and labelings.
INFO: Writing out MNI warps.
DEBUG: Traceback
Traceback (most recent call last):
  File "/home/user/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/cli/charm.py", line 172, in 
    main()
  File "/home/user/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/cli/charm.py", line 165, in main
    charm_main.run(subject_dir, args.T1, args.T2, args.registerT2, args.initatlas,
  File "/home/user/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/segmentation/charm_main.py", line 263, in run
    samseg.simnibs_segmentation_utils.saveWarpField(
  File "/home/user/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/segmentation/samseg/simnibs_segmentation_utils.py", line 275, in saveWarpField
    uncroppedMap[cropping] = np.squeeze(coordmapImage[:, :, :, c])
ValueError: could not broadcast input array from shape (178,231,232) into shape (178,231,232,1)
CRITICAL: Uncaught exception
ValueError: could not broadcast input array from shape (178,231,232) into shape (178,231,232,1)
```

**Comment by oulap** [comment]
I think the input volume you're passing to charm maybe has a singleton dimension in the end, i.e., the last ,1 in the shape. If you remove that before calling charm, that should do it.

I'll add this to the coming minor update of simnibs so that it gets squeezed automatically.

**Comment by iPsych** [comment]
@oulap where I should put the additional lines to remove singleton dimension?
Interestingly, one of two images with same header parameter works, the other shows above error.

**Comment by iPsych** [comment]
@oulap It did the trick! Thanks.
It's interesting that some tool save .nifti with modified dimension.
