### ISSUE TITLE
An expected error with headreco

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#14]
Dear Simnibs team, 

I got a new error with headreco. 

I attached the log files as well s the nii file. 

[headreco_log.txt](https://github.com/simnibs/simnibs/files/3914463/headreco_log.txt)
mri : https://www.dropbox.com/transfer/AAAAAKG0XaMOtFVuJlLrA2l6D9XvfZPUlE67IDITjxzt9oWEJ6xuGNs

Thanks for your help

Kind regards 
Takfarinas 

here are the last lines : 

PREPARING SURFACES FROM CAT12
========================================================================

Loading files...

Expanding left hemisphere
Expanding right hemisphere
Voxelizing left hemisphere
|##################################################|100% Completed
|##################################################|100% Completed
Voxelizing right hemisphere
|##################################################|100% Completed
|##################################################|100% Completed

Preparing to join hemispheres and extract ventricles
Joining CAT and SPM white matter segmentations
Preparing cerebellum
Preparing mask for joining hemispheres
Preparing ventricles
Joining hemispheres

Voxelizing gray matter
|##################################################|100% Completed
|##################################################|100% Completed
Decoupling volumes
Surface extraction: white matter
Surface extraction: ventricle
c:\users\33649\appdata\local\simnibs\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\msh\hmutils.py:1104: UserWarning: genfromtxt: Empty input file: "<itertools.islice object at 0x000001890B1F1B88>"
  vertices = np.genfromtxt(islice(f,0,hdr[0]))

c:\users\33649\appdata\local\simnibs\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\msh\hmutils.py:1106: UserWarning: genfromtxt: Empty input file: "<itertools.islice object at 0x000001890B1F1B88>"
  usecols=(1,2,3)).astype(np.uint)

Traceback (most recent call last):
  File "c:\users\33649\appdata\local\simnibs\miniconda3\envs\simnibs_env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\33649\appdata\local\simnibs\miniconda3\envs\simnibs_env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\33649\AppData\Local\SimNIBS\miniconda3\envs\simnibs_env\Scripts\headreco.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\users\33649\appdata\local\simnibs\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\cli\headreco.py", line 10, in main
    headmodel(sys.argv)
  File "c:\users\33649\appdata\local\simnibs\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\msh\headreco.py", line 450, in headmodel
    fsven = make_surface_and_shrink(vven.get_filename(), 5, 200, vd, 5, 0.5)
  File "c:\users\33649\appdata\local\simnibs\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\msh\headreco.py", line 1049, in make_surface_and_shrink
    ensure_distance=0.5, nsteps=2, deform="shrink")
  File "c:\users\33649\appdata\local\simnibs\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\msh\hmutils.py", line 2239, in deform_mesh
    node_normals = get_node_normals(vertices, faces, verts2consider)
  File "c:\users\33649\appdata\local\simnibs\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\msh\hmutils.py", line 2403, in get_node_normals
    triangle_normals = get_triangle_normals(vertices[faces])
  File "c:\users\33649\appdata\local\simnibs\miniconda3\envs\simnibs_env\lib\site-packages\simnibs\msh\hmutils.py", line 1069, in get_triangle_normals
    tnormals = np.cross(mesh[:,1,:]-mesh[:,0,:],mesh[:,2,:]-mesh[:,0,:]).astype(np.float)

**Comment by oulap** [comment]
I ran the data, and it finished without any errors. Can you try to do a clean re-run?

**Comment by tmedani** [comment]
> I ran the data, and it finished without any errors. Can you try to do a clean re-run?
Indeed, I cleaned the repo and the problem was solved.
Thank you.
