### ISSUE TITLE
library crash with matlab ones.

### ISSUE THREAD

**Issue by iPsych** [simnibs/simnibs#140]
charm can't run when matlab LD_LIBRARY_PATH is set in .bashrc
It works again when remove PATH setting. 
The issue happens no matter the simnibs path is preceding matlab ones or not.
```
Traceback (most recent call last):
  File "/home/ipsych/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/cli/charm.py", line 30, in <module>
    from simnibs import __version__
  File "/home/ipsych/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/__init__.py", line 21, in <module>
    from .mesh_tools import *
  File "/home/ipsych/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/mesh_tools/__init__.py", line 6, in <module>
    from .mesh_io import *
  File "/home/ipsych/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/mesh_tools/mesh_io.py", line 50, in <module>
    from . import cgal
  File "/home/ipsych/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/mesh_tools/cgal/__init__.py", line 1, in <module>
    from .create_mesh_surf import *
ImportError: /home/ipsych/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/mesh_tools/cgal/create_mesh_surf.cpython-39-x86_64-linux-gnu.so: undefined symbol: __gmpq_add
```

**Comment by oulap** [comment]
The LD_LIBRARY_PATH is probably preloading something that our cgal libraries were not compiled against.

If that's something you specifically need for matlab, I guess the easiest thing might be to write a small bash script that sets the LD_LIBRARY_PATH and then starts matlab.

**Comment by shawnxz** [comment]
I am encountering the very same error when I call run_simnibs in matlab, regardless of whether LD_LIBRARY_PATH is set in bash (to /lib64/libgmp.so) or not (by default). How should I solve this issue? Thanks!
