### ISSUE TITLE
multiprocessing bug

### ISSUE THREAD

**Issue by windyjunfeng** [simnibs/simnibs#240]
I find parallel running the tms optimization code in Linux is normal but error occurs in Windows. 
```
RuntimeError:
        An attempt has been made to start a new process before the current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your child processes and you have forgotten to use the proper idiom in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program is not going to be frozen to produce an executable.
```
After debugging the code, I find it runs from the start again when running the following code in Windows.
```
with multiprocessing.Pool(
                processes=n_workers,
                initializer=_set_up_tms_many_global_solver,
                initargs=(S, fn_coil, n_sims, D, post_pro, cond, field, roi)) as pool:
```
I think the difference of the way of building the subprocessing between Linux and Windows leads to the problem. Linux uses ''fork'' to build the subprocessing, which inherits most of the data from the parent process. However, Windows uses ''spawn'' to build the subprocessing, which copies all of data from the parent process.
So, I think it's a bug due to the system. Would you please modify the multiprocessing part of the code to make sure normal running in Windows? Thank you~

**Comment by diedrim** [comment]
As far as we understand, your code runs on Linus, but not on Windows. Can you clarify what you mean by "run from the start again"? Can you provide a script based on the ernie dataset, with which we can reproduce the error?

**Comment by windyjunfeng** [comment]
Thanks for your reply. Yes, the code can run on Linux **in parallel**, but it cannot run on Windows **in parallel**. In my opinion, the way of building the subprocess causes the problem. You can try the following codes on Windows. The meaning of "run from the start again" is run the following codes again.  
```
import os
from simnibs import opt_struct

# Initialize structure
tms_opt = opt_struct.TMSoptimize()
# Subject folder
tms_opt.subpath = 'm2m_ernie'
# Select output folder
tms_opt.pathfem = 'tms_optimization/'
# Select the coil model
tms_opt.fnamecoil = os.path.join('legacy_and_other','Magstim_70mm_Fig8.ccd')
# Select a target for the optimization
tms_opt.target = [-39.7, 7.5, 65.6]
# Optional: Use the MKL PARDISO solver
# Will make the simulations much faster
# but has large (approx 12GB) memory usage
tms_opt.solver_options = 'pardiso'
# Run optimization to get optimal coil position
opt_pos=tms_opt.run(cpus=2, save_mat=False)
```
The error is as follows.
```
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
Besides, if I define the above codes as a function  `main()` and call it by the following, error still occurs.
```
if __name__=='__main__':
    main()
```
The error is as follows.
```
AttributeError: Can't pickle local object 'TMSoptimize._direct_optimize.<locals>.postprocessing'
> d:\simnibs\simnibs_env\lib\site-packages\simnibs\simulation\fem.py(1906)tms_many_simulations()
-> with multiprocessing.Pool(
(Pdb) Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\simnibs\simnibs_env\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\simnibs\simnibs_env\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```
I sincerely hope you can come up with a way of running the codes on Windows! Thank you~

**Comment by diedrim** [comment]
Thank you for pointing that out.
Please set cpus=1 for now, until we find a solution.

**Comment by windyjunfeng** [comment]
OK, thank you for your reply. Look forward to your solution.
