### ISSUE TITLE
HDF reader for matlab v7.3 files

### ISSUE THREAD

**Issue by kirstinheise** [simnibs/simnibs#250]
SimNIBS 4.0.1 on M2 under Mac OS 14.1.2

I am attempting to run the Nx1.m example, i.e., using expand_to_center_surround, and it seems that an HDF reader needs to be called in mio.py. 

The error says
Warning: File '/private/var/folders/rx/9m03zpq15lx_pr649y3dw7_40000gr/T/tp46dd6f3e_0807_41c9_832c_678b7df45b4f.mat' not found. 
> In expand_to_center_surround (line 69) 
Error using expand_to_center_surround
There was an error running expand_to_center_surround:
 Traceback (most recent call last):
  File "...../SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/cli/expand_to_center_surround.py", line 85, in <module>
    main()
  File "...../SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/cli/expand_to_center_surround.py", line 52, in main
    mat = scipy.io.loadmat(os.path.abspath(os.path.realpath(os.path.expanduser(args.S))))
  File "...../SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/scipy/io/matlab/mio.py", line 225, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "...../SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/scipy/io/matlab/mio.py", line 80, in mat_reader_factory
    raise NotImplementedError('Please use HDF reader for matlab v7.3 files')
NotImplementedError: Please use HDF reader for matlab v7.3 files

Not sure if this is a problem specific to running Matlab on ARM/silicon or of interest to others?

-kirstin

**Comment by kirstinheise** [comment]
Thank you. Changing the default v7.3. option in the Matlab settings solved the issues as well.
