### ISSUE TITLE
Charm can't locate T1

### ISSUE THREAD

**Issue by ashaie** [simnibs/simnibs#266]
Everytime I try to run charm it quits and says can't locate the T1 file event though I am in the correct folder. I tried this in both 4.01 and 4.1

Traceback (most recent call last):
  File "C:\Users\Desktop\SimNIBS-4.1\simnibs_env\Lib\site-packages\simnibs\cli\charm.py", line 142, in <module>
    main()
  File "C:\Users\Desktop\SimNIBS-4.1\simnibs_env\Lib\site-packages\simnibs\cli\charm.py", line 132, in main
    charm_main.run(subject_dir, args.T1, args.T2, args.registerT2, args.initatlas,
  File "C:\Users\\Desktop\SimNIBS-4.1\simnibs_env\lib\site-packages\simnibs\segmentation\charm_main.py", line 128, in run
    _prepare_t1(T1, sub_files.reference_volume, force_qform, force_sform)
  File "C:\Users\A\Desktop\SimNIBS-4.1\simnibs_env\lib\site-packages\simnibs\segmentation\charm_main.py", line 708, in _prepare_t1
    raise FileNotFoundError(f"Could not find input T1 file: {T1}")
FileNotFoundError: Could not find input T1 file: org/T1.nii.gz
CRITICAL: Uncaught exception
FileNotFoundError: Could not find input T1 file: org/T1.nii.gz

**Comment by oulap** [comment]
Did you cd inside the folder where the T1 and T2 scans are, or one folder up? 

The path you're trying to input is "org/T1.nii.gz", i.e., you should be in a path that contains a folder called "org", which has the scans, when you call charm.

**Comment by ashaie** [comment]
Yes, cd'd inside that folder
C:\Users\Desktop\Documents\mida\org

and then used the command charm  org/T1.nii.gz

**Comment by ashaie** [comment]
thank you! I was one folder up.
