### ISSUE TITLE
SimNIBS 4.1 fails to install on macOS 10.13 and 10.14, which are documented as supported

### ISSUE THREAD

**Issue by seanm** [simnibs/simnibs#357]
It says here:

https://simnibs.github.io/simnibs/build/html/installation/simnibs_installer.html

"SimNIBS only supports MacOS versions ≥ 10.13 (High Sierra)"

Is this still correct?  I've installed SimNIBS 4.1 successfully on 10.15, 11, 12, 13, and 14. But it's failing on 10.13 and 10.14.

On my 10.14 machine:

```
Jun  6 17:56:11 builder21 Installer[12475]: Package Authoring Error: <background_scaling> has an unsupported MIME type: X-NSObject/NSNumber
Jun  6 17:56:11 builder21 Installer[12475]: Package Authoring Error: <background_alignment> has an unsupported MIME type: X-NSObject/NSNumber
Jun  6 17:56:11 builder21 Installer[12475]: Package Authoring Error: <layout-direction> has an unsupported MIME type: X-NSObject/NSNumber
Jun  6 17:56:17 builder21 installd[11878]: PackageKit: ----- Begin install -----
Jun  6 17:57:04 builder21 package_script_service[11882]: *** LOG MESSAGE QUOTA EXCEEDED - SOME MESSAGES FROM THIS PROCESS HAVE BEEN DISCARDED ***
Jun  6 17:58:13 builder21 package_script_service[11882]: *** LOG MESSAGE QUOTA EXCEEDED - SOME MESSAGES FROM THIS PROCESS HAVE BEEN DISCARDED ***
Jun  6 17:59:53 builder21 package_script_service[11882]: *** LOG MESSAGE QUOTA EXCEEDED - SOME MESSAGES FROM THIS PROCESS HAVE BEEN DISCARDED ***
Jun  6 18:00:01 builder21 installd[11878]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “simnibs_installer_macos.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/builder/Downloads/simnibs_installer_macos.pkg#simnibs_installer_macos.pkg, PKInstallPackageIdentifier=org.SimNIBS.4.1.0, NSLocalizedDescription=An error occurred while running scripts from the package “simnibs_installer_macos.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201csimnibs_installer_macos.pkg\U201d.";
	    NSURL = "file://localhost/Users/builder/Downloads/simnibs_installer_macos.pkg#simnibs_installer_macos.pkg";
	    PKInstallPackageIdentifier = "org.SimNIBS.4.1.0";
	}
Jun  6 18:00:01 builder21 Installer[12475]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Jun  6 18:00:01 builder21 Installer[12475]: Displaying 'Install Failed' UI.
Jun  6 18:00:01 builder21 Installer[12475]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
```

**Comment by oulap** [comment]
We build the installer on MacOS 12 and test it on MacOS 13 in our CI pipelines, so I would expect it to work on those older versions as well. Does the older SimNIBS version, i.e., v4.0.1, install on those machines? It also looks like it might only be the postinstall script that fails. Can you run any of the commands, like charm, in the bin-folder after the failed installation?

**Comment by seanm** [comment]
>Does the older SimNIBS version, i.e., v4.0.1, install on those machines?

Nope, seems about the same:

```
Jun 13 11:57:44 builder21 Installer[65721]: Package Authoring Error: <background_scaling> has an unsupported MIME type: X-NSObject/NSNumber
Jun 13 11:57:44 builder21 Installer[65721]: Package Authoring Error: <background_alignment> has an unsupported MIME type: X-NSObject/NSNumber
Jun 13 11:57:44 builder21 Installer[65721]: Package Authoring Error: <layout-direction> has an unsupported MIME type: X-NSObject/NSNumber
Jun 13 11:57:46 builder21 installd[65740]: PackageKit: ----- Begin install -----
Jun 13 11:59:06 builder21 installd[65740]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “simnibs_installer_macos-4.0.1.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/builder/Downloads/simnibs_installer_macos-4.0.1.pkg#simnibs_installer_macos.pkg, PKInstallPackageIdentifier=org.SimNIBS.4.0.1, NSLocalizedDescription=An error occurred while running scripts from the package “simnibs_installer_macos-4.0.1.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201csimnibs_installer_macos-4.0.1.pkg\U201d.";
	    NSURL = "file://localhost/Users/builder/Downloads/simnibs_installer_macos-4.0.1.pkg#simnibs_installer_macos.pkg";
	    PKInstallPackageIdentifier = "org.SimNIBS.4.0.1";
	}
Jun 13 11:59:07 builder21 Installer[65721]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Jun 13 11:59:07 builder21 Installer[65721]: Displaying 'Install Failed' UI.
Jun 13 11:59:07 builder21 Installer[65721]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
```


>Can you run any of the commands, like charm, in the bin-folder after the failed installation?

Seems not:

```
builder21:SimNIBS-4.1 builder$ ./simnibs_env/bin/charm --version
Traceback (most recent call last):
  File "/Users/builder/Applications/SimNIBS-4.1/./simnibs_env/bin/charm", line 5, in <module>
    from simnibs.cli.charm import main
  File "/Users/builder/Applications/SimNIBS-4.1/simnibs_env/lib/python3.9/site-packages/simnibs/__init__.py", line 30, in <module>
    from .utils.nnav import localite, softaxic, brainsight, ant
  File "/Users/builder/Applications/SimNIBS-4.1/simnibs_env/lib/python3.9/site-packages/simnibs/utils/nnav.py", line 18, in <module>
    from ..simulation import TMSLIST, POSITION
  File "/Users/builder/Applications/SimNIBS-4.1/simnibs_env/lib/python3.9/site-packages/simnibs/simulation/__init__.py", line 6, in <module>
    from .sim_struct import *
  File "/Users/builder/Applications/SimNIBS-4.1/simnibs_env/lib/python3.9/site-packages/simnibs/simulation/sim_struct.py", line 50, in <module>
    from . import fem
  File "/Users/builder/Applications/SimNIBS-4.1/simnibs_env/lib/python3.9/site-packages/simnibs/simulation/fem.py", line 16, in <module>
    from simnibs.simulation.tms_coil.tms_coil import TmsCoil
  File "/Users/builder/Applications/SimNIBS-4.1/simnibs_env/lib/python3.9/site-packages/simnibs/simulation/tms_coil/tms_coil.py", line 27, in <module>
    from simnibs.simulation.tms_coil.tms_coil_element import (
  File "/Users/builder/Applications/SimNIBS-4.1/simnibs_env/lib/python3.9/site-packages/simnibs/simulation/tms_coil/tms_coil_element.py", line 6, in <module>
    import fmm3dpy
  File "/Users/builder/Applications/SimNIBS-4.1/simnibs_env/lib/python3.9/site-packages/fmm3dpy/__init__.py", line 1, in <module>
    from .fmm3d import hfmm3d,lfmm3d,emfmm3d,stfmm3d,h3ddir,l3ddir,em3ddir,st3ddir,comperr,Output
  File "/Users/builder/Applications/SimNIBS-4.1/simnibs_env/lib/python3.9/site-packages/fmm3dpy/fmm3d.py", line 1, in <module>
    from . import hfmm3d_fortran as hfmm
ImportError: dlopen(/Users/builder/Applications/SimNIBS-4.1/simnibs_env/lib/python3.9/site-packages/fmm3dpy/hfmm3d_fortran.cpython-39-darwin.so, 2): Symbol not found: _aligned_alloc
  Referenced from: /Users/builder/Applications/SimNIBS-4.1/simnibs_env/lib/python3.9/site-packages/fmm3dpy/hfmm3d_fortran.cpython-39-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/builder/Applications/SimNIBS-4.1/simnibs_env/lib/python3.9/site-packages/fmm3dpy/hfmm3d_fortran.cpython-39-darwin.so
```

**Comment by oulap** [comment]
Thanks, that helps. Final question: are these macs running on Intel or M1?

**Comment by seanm** [comment]
Intel.  (arm64 was not supported until macOS 11.)

**Comment by oulap** [comment]
We had to recompile our own version of the fmm3dpy to make it compatible with arm64. Maybe that's causing problems for the older mac versions (although it's a bit weird as we do test on those). You can try either installing from source (but edit the environment file so that fmm3dpy is installed from pip), or just use the simnibs python interpreter from your broken installation to upgrade fmm3dpy using pip. Something like:

`simnibs_python -m pip install fmm3dpy
`
should work. Once that's done, try running charm again.

**Comment by seanm** [comment]
> Maybe that's causing problems for the older mac versions (although it's a bit weird as we do test on those).

Does this mean you don't reproduce on 10.13 yourself?

> You can try...

I personally am not too concerned about it... most of our customers use newer macOS than that.  You could simply update your website to say 10.15 is required as far as I'm concerned.

**Comment by oulap** [comment]
Our Azure pipeline runs tests on 10.13 and those pass so at least that error does not pop up during the CI runs. If it becomes a problem for you guys I can try to dig a bit more into it.

**Comment by seanm** [comment]
>Our Azure pipeline runs tests on 10.13 and those pass so at least that error does not pop up during the CI runs.

Hmmm, I guess it's something particular to the installer then...

>If it becomes a problem for you guys I can try to dig a bit more into it.

Thanks. I'll let you know if a customer ever encounters it. (Though I would first advise them to just update macOS, unless their hardware is too old.)

**Comment by seanm** [comment]
There have been no commits for 10 months, so what does "completed" mean here?

**Comment by TorgeW** [comment]
Hey, we are preparing a new release for SimNIBS. 
With this version, we will drop support for Intel Macs.
The documentation will be updated accordingly. 

I am sorry if this causes any inconvenience.

**Comment by seanm** [comment]
I'm curious why...?

**Comment by Kstoffer** [comment]
We dropped support for Intel Macs mainly because supporting them is a bit cumbersome as it requires us to build specific binaries for the packages that we manually compile for example fmm3d and petsc. So the decision was mainly pragmatic to limit support efforts and motivated by the fact that Apple no longer produces Intel Macs.
Also, in case you have an Intel Mac it is relatively easy to run the new SimNIBs version via a Linux docker container or any other type of virtualization like Parallels Desktop.
