### ISSUE TITLE
Installation for development fails

### ISSUE THREAD

**Issue by benecia2sj** [simnibs/simnibs#398]
Hello, I tried to install the simnibs as instructed in README.md, but it failed at the third stage `python -m pip install --editable` with the following error. I tried the installation on MacOS (Apple M3 Pro, Sonoma 14.2.1) and Linux, and both failed at the same stage. 

For MacOS, I used 

```
CONDA_SUBDIR=osx-64 conda env create -f environment_.yml -n <name_of_my_environment>
conda env config vars set CONDA_SUBDIR=osx-64 -n <name_of_my_environment>
conda activate <name_of_my_environment>
python -m pip install --editable .
```

For Linux, I used
```
conda env create -f environment_.yml -n <name_of_my_environment>
conda activate <name_of_my_environment>
python -m pip install --editable .
```

The error messages are

```
  Running setup.py develop for simnibs
    ERROR: Command errored out with exit status 1:
     command: /home/soojin/anaconda3/envs/simnibs/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/soojin/Gitrepo/simnibs/setup.py'"'"'; __file__='"'"'/home/soojin/Gitrepo/simnibs/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/soojin/Gitrepo/simnibs/
    Complete output (105 lines):
    /home/soojin/Gitrepo/simnibs/setup.py:11: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
      from distutils.dep_util import newer_group
    For maximum compatibility please make sure to include a `scheme` prefix in your URL (e.g. 'http://'). Given value: simnibs.org
    running develop
    /tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/setuptools/command/develop.py:42: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      easy_install.initialize_options(self)
    /tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    running egg_info
    writing simnibs.egg-info/PKG-INFO
    writing dependency_links to simnibs.egg-info/dependency_links.txt
    writing entry points to simnibs.egg-info/entry_points.txt
    writing requirements to simnibs.egg-info/requires.txt
    writing top-level names to simnibs.egg-info/top_level.txt
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'simnibs/segmentation/atlases/charm_atlas_mni'
    adding license file 'LICENSE.txt'
    writing manifest file 'simnibs.egg-info/SOURCES.txt'
    running build_ext
    /tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/soojin/Gitrepo/simnibs/simnibs/mesh_tools/cgal/polygon_mesh_processing.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    warning: simnibs/mesh_tools/cgal/polygon_mesh_processing.pyx:244:28: Unknown type declaration 'double' in annotation, ignoring
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cdef inline int int_max(int a, int b): return a if a >= b else b
    cdef inline int int_min(int a, int b): return a if a <= b else b
    
    @cython.boundscheck(False)
    @cython.wraparound(False)
    def interp_grid(np.ndarray[np.int_t, ndim=1] n_voxels,
                                  ^
    ------------------------------------------------------------
    
    simnibs/mesh_tools/cython_msh.pyx:19:30: Invalid type.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/soojin/Gitrepo/simnibs/setup.py", line 425, in <module>
        setup(ext_modules=extensions,
      File "/tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
        return run_commands(dist)
      File "/tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
        dist.run_commands()
      File "/tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
        self.run_command(cmd)
      File "/tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 956, in run_command
        super().run_command(command)
      File "/tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/setuptools/command/develop.py", line 113, in install_for_development
        self.run_command('build_ext')
      File "/tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
        self.distribution.run_command(command)
      File "/tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 956, in run_command
        super().run_command(command)
      File "/tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
        cmd_obj.run()
      File "/home/soojin/Gitrepo/simnibs/setup.py", line 362, in run
        self.extension = cythonize(self.extensions)
      File "/tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
        cythonize_one(*args)
      File "/tmp/pip-build-env-44jy21nr/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: simnibs/mesh_tools/cython_msh.pyx
    Compiling simnibs/mesh_tools/cython_msh.pyx because it changed.
    Compiling simnibs/segmentation/_marching_cubes_lewiner_cy.pyx because it changed.
    Compiling simnibs/segmentation/_cat_c_utils.pyx because it changed.
    Compiling simnibs/segmentation/_thickness.pyx because it changed.
    Compiling simnibs/simulation/petsc_solver.pyx because it changed.
    Compiling simnibs/mesh_tools/cgal/create_mesh_surf.pyx because it changed.
    Compiling simnibs/mesh_tools/cgal/create_mesh_vol.pyx because it changed.
    Compiling simnibs/mesh_tools/cgal/cgal_misc.pyx because it changed.
    Compiling simnibs/mesh_tools/cgal/polygon_mesh_processing.pyx because it changed.
    [1/9] Cythonizing simnibs/mesh_tools/cgal/cgal_misc.pyx
    [2/9] Cythonizing simnibs/mesh_tools/cgal/create_mesh_surf.pyx
    [3/9] Cythonizing simnibs/mesh_tools/cgal/create_mesh_vol.pyx
    [4/9] Cythonizing simnibs/mesh_tools/cgal/polygon_mesh_processing.pyx
    [5/9] Cythonizing simnibs/mesh_tools/cython_msh.pyx
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/soojin/anaconda3/envs/simnibs/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/soojin/Gitrepo/simnibs/setup.py'"'"'; __file__='"'"'/home/soojin/Gitrepo/simnibs/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

Could you please help me resolve the installation issue? Thank you very much!

**Comment by TorgeW** [comment]
Duplicate https://github.com/simnibs/simnibs/issues/393
