### ISSUE TITLE
python -m pip install . fails 

### ISSUE THREAD

**Issue by DanieleRe** [simnibs/simnibs#409]
Hi there,

I am trying to install the environment as suggested from the readme file but I run to few problems:

I create and activate it successfully the environment but when I have to launch python -m pip install --editable . I receive the following error

`   File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: simnibs/mesh_tools/cython_msh.pyx
      /tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py:983: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `simnibs` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
      
      !!
        cmd_obj.run()
      Compiling simnibs/mesh_tools/cython_msh.pyx because it changed.
      Compiling simnibs/segmentation/_marching_cubes_lewiner_cy.pyx because it depends on /tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      Compiling simnibs/segmentation/_cat_c_utils.pyx because it depends on /tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      Compiling simnibs/segmentation/_thickness.pyx because it depends on /tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      Compiling simnibs/simulation/petsc_solver.pyx because it depends on /tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      Compiling simnibs/mesh_tools/cgal/create_mesh_surf.pyx because it depends on /tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      Compiling simnibs/mesh_tools/cgal/create_mesh_vol.pyx because it depends on /tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      Compiling simnibs/mesh_tools/cgal/cgal_misc.pyx because it depends on /tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      Compiling simnibs/mesh_tools/cgal/polygon_mesh_processing.pyx because it depends on /tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      [1/9] Cythonizing simnibs/mesh_tools/cython_msh.pyx
      Traceback (most recent call last):
        File "/home/daniele/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/daniele/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/daniele/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 453, in build_editable
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 425, in <module>
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 153, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 355, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 278, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 305, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "<string>", line 362, in run
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-0cg1wglu/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: simnibs/mesh_tools/cython_msh.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for simnibs
Failed to build simnibs
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (simnibs)
`

so I decided to just run python -m pip install . but I get the following one:

`  Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef inline int int_max(int a, int b): return a if a >= b else b
      cdef inline int int_min(int a, int b): return a if a <= b else b
      
      @cython.boundscheck(False)
      @cython.wraparound(False)
      def interp_grid(np.ndarray[np.int_t, ndim=1] n_voxels,
                                    ^
      ------------------------------------------------------------
      
      simnibs/mesh_tools/cython_msh.pyx:19:30: Invalid type.
      Compiling simnibs/mesh_tools/cython_msh.pyx because it changed.
      Compiling simnibs/segmentation/_marching_cubes_lewiner_cy.pyx because it depends on /tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      Compiling simnibs/segmentation/_cat_c_utils.pyx because it depends on /tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      Compiling simnibs/segmentation/_thickness.pyx because it depends on /tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      Compiling simnibs/simulation/petsc_solver.pyx because it depends on /tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      Compiling simnibs/mesh_tools/cgal/create_mesh_surf.pyx because it depends on /tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/Cython/Includes/libcpp/utility.pxd.
      Compiling simnibs/mesh_tools/cgal/create_mesh_vol.pyx because it depends on /tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/Cython/Includes/libcpp/utility.pxd.
      Compiling simnibs/mesh_tools/cgal/cgal_misc.pyx because it depends on /tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/Cython/Includes/libcpp/utility.pxd.
      Compiling simnibs/mesh_tools/cgal/polygon_mesh_processing.pyx because it depends on /tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/Cython/Includes/libcpp/utility.pxd.
      [1/9] Cythonizing simnibs/mesh_tools/cython_msh.pyx
      Traceback (most recent call last):
        File "/home/daniele/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/daniele/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/daniele/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 425, in <module>
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "<string>", line 362, in run
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-irotydwe/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: simnibs/mesh_tools/cython_msh.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simnibs
Failed to build simnibs
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (simnibs)
`

Does anyone know how to solve this issue?

Thanks :)

**Comment by jduemose** [comment]
Hi, this sounds like a similar problem as in #393. Can you try the suggested fix and see if it resolves your issue?
