### ISSUE TITLE
UQ with normal distribution

### ISSUE THREAD

**Issue by mchannah13** [simnibs/simnibs#46]
Hello,

I was wondering if it were possible to use normally distributed variables within the uncertainty quantification? I realise this isn't recommended, but is it possible to normally distribute the variables and obtain results? And further to omit ay negative conductivities whilst it being normally distributed.

I tried running with "normal", instead of "beta", however I come across an error "simnibs.cython_code.petsc_solver.SolverError: There was an error during the solve.
PETSc returned error code: 1"

Thank you for any help!

**Comment by Kstoffer** [comment]
I am thinking that the error is caused by negative conductivity as you are also alluding to. At the moment we do only support the Normal and Beta distribution and do not have immediate plans to extend this. I believe it would not be entirely trivial to extend the support to a truncated Normal as it would likely also mean that another class of polynomials (than the Hermite for Normal case) would have to be introduced, and I am not really aware of work using the truncated Normal distribution in GPC.  Anyways, our initial belief was that a Beta distribution with appropriate parameters can well approximate the expected distribution of conductivities in particular considering the great uncertainty of the estimates presented in the literature.
Best,
Kristoffer

**Comment by mchannah13** [comment]
Hi Kristoffer,

Thank you very much for your reply and help.

We have come across another problem, using beta distributions with larger conductivity variations (firstly takes hours with >100 iterations, but I assume this is normal), but many times it also fails with the error "Uncaught exception
numpy.linalg.LinAlgError: Matrix is singular." Do you know why this might be or how to avoid this problem?

Thank you very much in advance!


Longer error below:

[ simnibs 3.2.1 - 2020-12-14 22:06:44,906 - 2825 ]DEBUG: Traceback
Traceback (most recent call last):
  File "/home/c1219560/SimNIBS-3.2s/simnibs_env/lib/python3.7/site-packages/simnibs/cli/run_simnibs.py", line 29, in <module>
    main()
  File "/home/c1219560/SimNIBS-3.2s/simnibs_env/lib/python3.7/site-packages/simnibs/cli/run_simnibs.py", line 25, in main
    run_simnibs(args.simnibs_file, args.cpus)
  File "/home/c1219560/SimNIBS-3.2s/simnibs_env/lib/python3.7/site-packages/simnibs/simulation/run_simnibs.py", line 27, in run_simnibs
    out = p.run(cpus=cpus)
  File "/home/c1219560/SimNIBS-3.2s/simnibs_env/lib/python3.7/site-packages/simnibs/simulation/sim_struct.py", line 252, in run
    fn = PL.run_simulation(simu_name, cpus=cpus, view=self.open_in_gmsh)
  File "/home/c1219560/SimNIBS-3.2s/simnibs_env/lib/python3.7/site-packages/simnibs/simulation/sim_struct.py", line 1609, in run_simulation
    return self.run_gpc(fn_simu, cpus=cpus)
  File "/home/c1219560/SimNIBS-3.2s/simnibs_env/lib/python3.7/site-packages/simnibs/simulation/sim_struct.py", line 1660, in run_gpc
    self, fn_simu, cpus=cpus, tissues=tissues, eps=eps)
  File "/home/c1219560/SimNIBS-3.2s/simnibs_env/lib/python3.7/site-packages/simnibs/simulation/gpc.py", line 649, in run_tcs_gpc
    min_iter=min_iter)
  File "/home/c1219560/SimNIBS-3.2s/simnibs_env/lib/python3.7/site-packages/simnibs/pygpc/adaptive.py", line 299, in run_reg_adaptive_grid
    coeffs, eps_gpc = regobj.expand(RES)
  File "/home/c1219560/SimNIBS-3.2s/simnibs_env/lib/python3.7/site-packages/simnibs/pygpc/adaptive.py", line 129, in expand
    errors[i] = _k_fold_cv_regression(A, data, regression_fun)
  File "/home/c1219560/SimNIBS-3.2s/simnibs_env/lib/python3.7/site-packages/simnibs/pygpc/adaptive.py", line 90, in _k_fold_cv_regression
    x = regression_function(A[~g, :], data[~g, :])
  File "/home/c1219560/SimNIBS-3.2s/simnibs_env/lib/python3.7/site-packages/simnibs/pygpc/adaptive.py", line 68, in _tikhonov
    overwrite_a=True)
  File "/home/c1219560/SimNIBS-3.2s/simnibs_env/lib/python3.7/site-packages/scipy/linalg/basic.py", line 250, in solve
    _solve_check(n, info)
  File "/home/c1219560/SimNIBS-3.2s/simnibs_env/lib/python3.7/site-packages/scipy/linalg/basic.py", line 31, in _solve_check
    raise LinAlgError('Matrix is singular.')
numpy.linalg.LinAlgError: Matrix is singular.
[ simnibs 3.2.1 - 2020-12-14 22:06:45,016 - 2825 ]CRITICAL: Uncaught exception
numpy.linalg.LinAlgError: Matrix is singular.

**Comment by Kstoffer** [comment]
How large is the range of conductivities you use?
We do expect it to have numerical troubles with the polynomials if the range is high (matrix will be ill conditioned).
With respect to the speed of simulations we would recommend using the paradiso solver in case you have sufficient memory >12GB this should be much more efficient.
Best,
Kristoffer

**Comment by mchannah13** [comment]
Hi Kristoffer,

Thank you again for your reply, I am very grateful for your help. The range of conductivities for GM and scalp is 0.001 - 0.8, for example, with  a smaller range for WM and skull - is this range too large? Is there anyway to overcome this whilst using a large range? For some of the simulations for example it seems to work with no issues, but I'm unsure what the difference between those that work and those that dont are.

Thank you for the suggesting the Paradiso solver, thats very helpful.

Thanks again.

**Comment by Kstoffer** [comment]
Sorry, I jumped the gun a bit there, actually using the pardiso solver is not expected to improve the performance in this case as the right hand side in the FEM cannot be reused across simulations so I guess you will have to live with it being rather slow at the moment.
