### ISSUE TITLE
OpenGL + MacOS Big Sur

### ISSUE THREAD

**Issue by harrodjordan** [simnibs/simnibs#47]
Less of an issue and more of a heads up for anyone else who might run into this issue - If you're running MacOS Big Sur and try to open SimNIBS after installing according to the instructions, you may run into this error traceback. 

It turns out that updating to MacOS Big Sur changes the organization of your system libraries, making SimNIBS (or anything else running OpenGL) unable to open the GUI while running Python 3.7. [Based on this issue](https://github.com/PixarAnimationStudios/USD/issues/1257) upgrading to Python 3.9 fixes the issue, however, the MacOS installation instructions don't have a clear way of doing that without changing your anaconda path to the miniconda installation that comes with SimNIBS and then updating the environment. 

The fix that worked for me was going into 

`/usr/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/platform/ctypesloader.py `

and changing 

`fullName = util.find_library( name )`

to 

`fullName = '/System/Library/Frameworks/OpenGL.framework/OpenGL'`

```
(base) laptop:bin me$ simnibs_gui
Traceback (most recent call last):
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 38, in GL
    mode=ctypes.RTLD_GLOBAL 
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/platform/ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ('dlopen(OpenGL, 10): image not found', 'OpenGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/simnibs/cli/simnibs_gui.py", line 2, in <module>
    from simnibs.GUI.main_gui import start_gui
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/simnibs/GUI/main_gui.py", line 34, in <module>
    from . import electrodeGUI
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/simnibs/GUI/electrodeGUI.py", line 27, in <module>
    from OpenGL import GL, GLU
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 32, in _load
    plugin.install(globals())
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 62, in GetCurrentContext
    return self.CGL.CGLGetCurrentContext 
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 45, in CGL
    def CGL(self): return self.GL
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/Users/me/Applications/SimNIBS/miniconda3/envs/simnibs_env/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 41, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', 'dlopen(OpenGL, 10): image not found', 'OpenGL', None)
```

**Comment by Kstoffer** [comment]
This was already implemented as a dirty workaround in 3.2.2. We still consider this a temporary workaround but it should be working.
