### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by pedrohenrique1992** [simnibs/simnibs#87]
I am trying to install in Ubuntu 20.04, but I found this during installation

Installing SimNIBS 3.2.6 to /root/SimNIBS-3.2
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/root/SimNIBS-3.2/simnibs_env/bin/postinstall_simnibs", line 8, in <module>
    sys.exit(main())
  File "/root/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/cli/postinstall_simnibs.py", line 1051, in main
    args.associate_files
  File "/root/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/cli/postinstall_simnibs.py", line 854, in start_gui
    raise Exception('Post-installation cancelled by user')
Exception: Post-installation cancelled by user

How to fix this issue

**Comment by Kstoffer** [comment]
This might be related to the version on libstdc++ being incompatible with the system version, can you try to preload the version in your system.
you can do that with something like (prior to running the post-install in a terminal window):

LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6
If you dont have that file on your system you should be avle to install via: "sudo apt install libstdc++6"
Note that the name of that file might be slightly different on your system (you can also try the version without .6).

Best,
Kristoffer

**Comment by oulap** [comment]
I'm closing this due to inactivity. Feel free to re-open if you still have problems.
