### ISSUE TITLE
assertion fail in simnibs/msh/headreco.py:1092 , headreco version 3.05

### ISSUE THREAD

**Issue by vfonov** [simnibs/simnibs#9]
I came across following error:
Running: 
`headreco all --cat_no_print <name> <input.nii>`
.....

crashed with the following message:
```
....
Info    : Stopped on Tue Sep 17 17:48:55 2019
Gmsh failed meshing one or more surfaces. Doing uniform remeshing and retrying
Remeshing wm.stl
Remeshing gm.stl
Remeshing csf.stl
Remeshing bone.stl
Remeshing skin.stl
Remeshing eyes.stl
Remeshing cavities.stl
Remeshing ventricles.stl
Decoupling










Traceback (most recent call last):
  File "/data/data05/vfonov/conda/envs/simnibs_env/bin/headreco", line 10, in <module>
    sys.exit(main())
  File "/data/data05/vfonov/conda/envs/simnibs_env/lib/python3.7/site-packages/simnibs/cli/headreco.py", line 10, in main
    headmodel(sys.argv)
  File "/data/data05/vfonov/conda/envs/simnibs_env/lib/python3.7/site-packages/simnibs/msh/headreco.py", line 668, in headmodel
    vmsh = make_volume_mesh(args.subject_id, surfaces, subject_dir)
  File "/data/data05/vfonov/conda/envs/simnibs_env/lib/python3.7/site-packages/simnibs/msh/headreco.py", line 1864, in make_volume_mesh
    files["ventricles"])
  File "/data/data05/vfonov/conda/envs/simnibs_env/lib/python3.7/site-packages/simnibs/msh/headreco.py", line 1092, in decouple_wm_gm_ventricles
    assert isinstance(wm, str) and os.path.isfile(wm)
AssertionError
```

`headreco --version` outputs 3.0.5

**Comment by tmedani** [comment]
Hi, 

I'm also interested in this issue. 
I think this is due to the mesh resolution. 
Maybe your surfaces are too close and then the tesselation could not be done correctly. 
You can try the option -v with high resolution. 

I think also that you don't need to re-segment again, 
maybe the command: headreco surfacemesh subID and volume mesh subID should be sufficient.

Waiting for the answer of the developers. 

Thanks

**Comment by guilhermebs** [comment]
Sometimes, meshfix cannot decouple the surfaces and so gmsh fails to create the volumetric mesh. 

As mentioned above, the `-v` argument, that controls the density of the mesh, can help in these cases. 
You can either 
1. Delete the `m2m_<subID>` folder and run `headreco all` again with, for example `-v 1` or
2. Manually re-run the `preparecat` `surfacemesh` and `volumemesh` steps. Contrary to what is mentioned above, these commands require more arguments than just the subject ID, try for example `headreco preparecat -h` for help.

**Comment by seepideeh** [comment]
hi
I use this command 
> headreco all --cat ernie org/ernie_T1.nii.gz org/ernie_T2.nii.gz

  But I get this error:

> Traceback (most recent call last):
  File "/home/sepideh/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/nibabel/loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sepideh/simnibs data/ernie/m2m_ernie/segment/cat/wcattemplate_brainstem_hammers.nii
 During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
 File/home/sepideh/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/cli/headreco.py", line 13, in <module>
main()
  File "/home/sepideh/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/cli/headreco.py", line 10, in main
    headmodel(sys.argv)
  File "/home/sepideh/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/msh/headreco.py", line 330, in headmodel
    nib.save(nib.load(src), os.path.join(templates_dir, k+".gz"))
  File "/home/sepideh/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: '/home/sepideh/simnibs data/ernie/m2m_ernie/segment/cat/wcattemplate_brainstem_hammers.nii
