### ISSUE TITLE
ValueError: all the input array dimensions except for the concatenation axis must match exactly

### ISSUE THREAD

**Issue by reubebe** [simnibs/simnibs#97]
I am wondering what may be the cause, I got the same error with two different mac books

------------------------------------------------------------------------
Running job #1
------------------------------------------------------------------------
Running 'Deformations'
cattemplate_CC_hammers	1,1,1
cattemplate_brainstem_hammers	1,1,1
cattemplate_cerebellum_hammers	1,1,1
cattemplate_fornix_JHU	1,1,1
cattemplate_ventricles_lateral_hammers	1,1,1
cattemplate_ventricles_third_hammers	1,1,1
cattemplate_thalamus_harvard	1,1,1
Template_1_IXI555_MNI152	1,1,1	2,1,1
Done    'Deformations'
Done

Binarizing tissue probability maps
Traceback (most recent call last):
  File "/Users/addison/Applications/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/cli/headreco.py", line 13, in <module>
    main()
  File "/Users/addison/Applications/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/cli/headreco.py", line 10, in main
    headmodel(sys.argv)
  File "/Users/addison/Applications/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/msh/headreco.py", line 277, in headmodel
    masks = hmu.binarize([nib.load(v).get_data() for v in fcat])
  File "/Users/addison/Applications/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/msh/hmutils.py", line 781, in binarize
    imgs = np.concatenate(tuple([v[...,np.newaxis] for v in volsi]), axis=3)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
Reubens-MacBook-Pro:conv addison$

**Comment by oulap** [comment]
Hi,
Could you send the whole headreco_log.html to support@simnibs.org, so we can have a look?
Thanks!

**Comment by reubebe** [comment]
log file

**Comment by oulap** [comment]
Hi,

It seems the log file got lost on the way. You can also email it to support@simnibs.org if that's easier.
